### ISSUE TITLE
I think this might be mispackaged?

### ISSUE THREAD

**Issue by rcrooks** [ImADrafter/Down-Under-Theme#1]
Installs but not available as a color theme. Sorry, I didn't dig to see what the problem might be.
Looks great from the screenshot though.

**Comment by ImADrafter** [comment]
Hi @rcrooks ! It seems that you were totally right, thank you for make me know about this. It was missing a displayName property. A new version with the fix has been published so you should be able to use it from the vscode store.

If you have any more issues, or suggestions, feel free to contact with me again. :smile:

**Comment by rcrooks** [comment]
That’s great, Marcos. Look forward to trying it out.

Robert

Robert Crooks
Director of Learning Services
Brightcove, Inc
